import Head from "next/head";
import Home1 from "./home";

export default function Home() {
  return (
    <>
      <Head>
        <title>PFWSMC</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Home1 />
    </>
  );
}
